name: example-environment
channels:
  - conda-forge
dependencies:
  - python3.7
  - numpy
  - pip
  - pip:
    - jinja2==3.0.3
    - voila
    - ipywidgets
    - matplotlib
    - scipy
    - IPython
    - pandas
    
